### ISSUE TITLE
works on windows? 

### ISSUE THREAD

**Issue by serangelicloud** [Mr3rf1/SecPhoto#1]
good day, im interested in contributing but i was wondering, does the script work on windows? and if it does do i need to follow different steps?

**Comment by Mr3rf1** [comment]
Yeah, it works on windows.
you have to install python first. and then clone the source code to your local machine.
and after that you have to install dependencies: python(or py) -m pip install -r requirements.txt
and finally run it:‌ python SecPhoto.py -Sid <username of target chat>

**Comment by Mr3rf1** [comment]
@serangelicloud Yeah, it works on windows.
you have to install python first. and then clone the source code to your local machine.
and after that you have to install dependencies: python(or py) -m pip install -r requirements.txt
and finally run it:‌ python SecPhoto.py -Sid

**Comment by Mr3rf1** [comment]
> good day, im interested in contributing but i was wondering, does the script work on windows? and if it does do i need to follow different steps?

@serangelicloud Yeah, it works on windows.
you have to install python first. and then clone the source code to your local machine.
and after that you have to install dependencies: python(or py) -m pip install -r requirements.txt
and finally run it:‌ python SecPhoto.py -Sid
